name: Build and Push Docker images to GHCR

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Node.js image
        run: |
          docker build -f Dockerfile.node -t ghcr.io/sistemas-muy-poco-distribuidos/weather-node:latest .
          docker push ghcr.io/sistemas-muy-poco-distribuidos/weather-node:latest

      - name: Build and push Python image
        run: |
          docker build -f Dockerfile.python -t ghcr.io/sistemas-muy-poco-distribuidos/weather-python:latest .
          docker push ghcr.io/sistemas-muy-poco-distribuidos/weather-python:latest
